name: carvilla-webapp

on: 
  push: 
    branches: 
      - main 
jobs: 
    build-and-deploy: 
        runs-on: ubuntu-latest 
        steps: 
            - name: Checkout 
              uses: actions/checkout@v1 
            - name: Configure AWS Credentials 
              uses: aws-actions/configure-credentials@v1 
              with: 
                aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
                aws-secrect-access-key-id: ${{ secrets.SECRET_ACCESS_KEY_ID }} 
                aws-region: us-east-1 
                
            - name: Deploy static site to S3 bucket 
              run: aws s3 sync . s3://carvilla-webapp --delete # Change bucket name
